using TMPro;
using UnityEngine;

namespace Comibast
{
    /// <summary>
    /// だ计恨z
    /// </summary>
    public class ScoreManager : MonoBehaviour
    {
        public static int addScore = 2;

        private string nameBasketball = "xy";
        private TextMeshProUGUI textScore;
        private int totalScore;

        private void Awake()
        {
            textScore = GameObject.Find("だ计").GetComponent<TextMeshProUGUI>();
        }

        private void OnTriggerEnter(Collider other)
        {
            if (other.name.Contains(nameBasketball))
            {
                AddScore();
            }
        }

        private void AddScore()
        {
            totalScore += addScore;
            textScore.text = "SCORE " + totalScore;
        }

        /// <summary>
        /// 跑螭兰
        /// </summary>
        /// <param name="scoreToChange">n跑螵氦兰</param>
        private void ChangeScore(int scoreToChange)
        {
            addScore = scoreToChange;
        }
    }

}
